
export default {
  "视频技术": [
    {
      "id": 1,
      "serviceId": "swdae2133321",
      "serviceName": "视频活体检测",
      "requestUrl": "https://www.yzsophia.com/ai/hwface/vidioVerify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 125,
      "serviceId": "swdae2133445",
      "serviceName": "视频公众人物识别查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/getVideoFace",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 126,
      "serviceId": "swdae2133446",
      "serviceName": "视频范标签提取查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/getVideoTags",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 127,
      "serviceId": "swdae2133447",
      "serviceName": "视频OCR文字查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/getVideoText",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 128,
      "serviceId": "swdae2133448",
      "serviceName": "视频分类查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/getVideoType",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 129,
      "serviceId": "swdae2133449",
      "serviceName": "视频语音识别查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/getVideoVoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 130,
      "serviceId": "swdae2133450",
      "serviceName": "视频内容解析结果查询",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/queryAnalysisResult",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 131,
      "serviceId": "swdae2133451",
      "serviceName": "百度视频审核查询接口",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/queryCheckResult",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 132,
      "serviceId": "swdae2133452",
      "serviceName": "百度视频内容解析接口",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/videoAnalysis",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 133,
      "serviceId": "swdae2133453",
      "serviceName": "百度视频审核接口",
      "requestUrl": "https://www.yzsophia.com/ai/bdvideo/videoCheck",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 5,
      "aiName": "视频技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ],
  "语音技术": [
    {
      "id": 15,
      "serviceId": "swdae2133335",
      "serviceName": "年龄评估",
      "requestUrl": "https://www.yzsophia.com/ai/voice/ageDiscern",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 16,
      "serviceId": "swdae2133336",
      "serviceName": "上传语音文件返回中文识别结果",
      "requestUrl": "https://www.yzsophia.com/ai/voice/asr",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 17,
      "serviceId": "swdae2133337",
      "serviceName": "上传实时语音文件返回中文识别结果",
      "requestUrl": "https://www.yzsophia.com/ai/voice/asrByRt",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 18,
      "serviceId": "swdae2133338",
      "serviceName": "语音评测",
      "requestUrl": "https://www.yzsophia.com/ai/voice/evaluation",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 19,
      "serviceId": "swdae2133339",
      "serviceName": "歌曲识别",
      "requestUrl": "https://www.yzsophia.com/ai/voice/songDiscern",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 20,
      "serviceId": "swdae2133340",
      "serviceName": "上传文字返回语音合成文件",
      "requestUrl": "https://www.yzsophia.com/ai/voice/tts",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "灵云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 134,
      "serviceId": "swdae2133454",
      "serviceName": "实时语音识别模拟",
      "requestUrl": "https://www.yzsophia.com/ai/voice/audioAsrCt",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 135,
      "serviceId": "swdae2133455",
      "serviceName": "关键词检索",
      "requestUrl": "https://www.yzsophia.com/ai/voice/detectKeyword",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 136,
      "serviceId": "swdae2133456",
      "serviceName": "查询上传录音文件返回的识别结果",
      "requestUrl": "https://www.yzsophia.com/ai/voice/getVoiceFileAsrResult",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 137,
      "serviceId": "swdae2133457",
      "serviceName": "百度UNIT--机器人对话",
      "requestUrl": "https://www.yzsophia.com/ai/voice/robotDialogue",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 138,
      "serviceId": "swdae2133458",
      "serviceName": "音频鉴黄/音频敏感词检测接口",
      "requestUrl": "https://www.yzsophia.com/ai/voice/sensitiveWord",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 139,
      "serviceId": "swdae2133459",
      "serviceName": "在线语音合成",
      "requestUrl": "https://www.yzsophia.com/ai/voice/text2audioTTs",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 140,
      "serviceId": "swdae2133460",
      "serviceName": "上传短语音文件返回中文识别结果",
      "requestUrl": "https://www.yzsophia.com/ai/voice/voiceAsr",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 141,
      "serviceId": "swdae2133461",
      "serviceName": "上传实时语音文件返回中文识别结果",
      "requestUrl": "https://www.yzsophia.com/ai/voice/voiceAsrCt",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 142,
      "serviceId": "swdae2133462",
      "serviceName": "上传录音文件返回识别内容任务",
      "requestUrl": "https://www.yzsophia.com/ai/voice/voiceFileAsr",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 183,
      "serviceId": "swdae2133503",
      "serviceName": "创建视频-动态封面任务-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/createDynamicCover",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 184,
      "serviceId": "swdae2133504",
      "serviceName": "创建视频-静态封面任务-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/createStaticCover",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 185,
      "serviceId": "swdae2133505",
      "serviceName": "创建视频内容分析-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/createVideoAnalysis",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 186,
      "serviceId": "swdae2133506",
      "serviceName": "获取任务处理结果-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getAnalysisResult",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 187,
      "serviceId": "swdae2133507",
      "serviceName": "动态封面提取-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getDynamicCover",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 188,
      "serviceId": "swdae2133508",
      "serviceName": "通用物体识别-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getGeneralObject",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 189,
      "serviceId": "swdae2133509",
      "serviceName": "静态封面提取-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getStaticCover",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 190,
      "serviceId": "swdae2133510",
      "serviceName": "节目、标识识别-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getVideoIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 191,
      "serviceId": "swdae2133511",
      "serviceName": "地点、关键词识别-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/getVideoPlace",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 192,
      "serviceId": "swdae2133512",
      "serviceName": "获取视频任务处理状态-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/queryAnalysisStatus",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 193,
      "serviceId": "swdae2133513",
      "serviceName": "视频人物识别查询-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/queryVideoFace",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 194,
      "serviceId": "swdae2133514",
      "serviceName": "视频分类查询-阿里",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/queryVideoType",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 195,
      "serviceId": "swdae2133515",
      "serviceName": "上传文件到oss",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/upload",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 196,
      "serviceId": "swdae2133516",
      "serviceName": "视频活体检测",
      "requestUrl": "https://www.yzsophia.com/ai/alivideo/vidioVerify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 2,
      "aiName": "语音技术",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ],
  "图片识别": [
    {
      "id": 83,
      "serviceId": "swdae2133403",
      "serviceName": "动物识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/animalIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 84,
      "serviceId": "swdae2133404",
      "serviceName": "植物识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/botanyIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 85,
      "serviceId": "swdae2133405",
      "serviceName": "品牌logo识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/brandLogo",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 86,
      "serviceId": "swdae2133406",
      "serviceName": "车辆属性识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/carAttribute",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 87,
      "serviceId": "swdae2133407",
      "serviceName": "车辆损伤识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/carDamage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 88,
      "serviceId": "swdae2133408",
      "serviceName": "车型识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/carIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 89,
      "serviceId": "swdae2133409",
      "serviceName": "车辆分割",
      "requestUrl": "https://www.yzsophia.com/ai/image/carSegmentation",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 90,
      "serviceId": "swdae2133410",
      "serviceName": "车辆检测",
      "requestUrl": "https://www.yzsophia.com/ai/image/carTestIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 91,
      "serviceId": "swdae2133411",
      "serviceName": "图片审核",
      "requestUrl": "https://www.yzsophia.com/ai/image/censor",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 92,
      "serviceId": "swdae2133412",
      "serviceName": "图像分类模型",
      "requestUrl": "https://www.yzsophia.com/ai/image/classifyModel",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 93,
      "serviceId": "swdae2133413",
      "serviceName": "黑白图像上色",
      "requestUrl": "https://www.yzsophia.com/ai/image/colourize",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 94,
      "serviceId": "swdae2133414",
      "serviceName": "图像对比度增强",
      "requestUrl": "https://www.yzsophia.com/ai/image/contrastenhance",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 95,
      "serviceId": "swdae2133415",
      "serviceName": "货币识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/currencyIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 96,
      "serviceId": "swdae2133416",
      "serviceName": "图像清晰度增强",
      "requestUrl": "https://www.yzsophia.com/ai/image/definitionenhance",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 97,
      "serviceId": "swdae2133417",
      "serviceName": "图像去雾",
      "requestUrl": "https://www.yzsophia.com/ai/image/dehaze",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 98,
      "serviceId": "swdae2133418",
      "serviceName": "果蔬识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/gardenStuffIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 99,
      "serviceId": "swdae2133419",
      "serviceName": "通用物体和场景识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/generalSceneIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 100,
      "serviceId": "swdae2133420",
      "serviceName": "图像主体检测",
      "requestUrl": "https://www.yzsophia.com/ai/image/imageBody",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 101,
      "serviceId": "swdae2133421",
      "serviceName": "图像修复",
      "requestUrl": "https://www.yzsophia.com/ai/image/inpainting",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 102,
      "serviceId": "swdae2133422",
      "serviceName": "地标识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/landmarkIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 103,
      "serviceId": "swdae2133423",
      "serviceName": "人流量统计",
      "requestUrl": "https://www.yzsophia.com/ai/image/personFlowSti",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 104,
      "serviceId": "swdae2133424",
      "serviceName": "图像无损放大",
      "requestUrl": "https://www.yzsophia.com/ai/image/qualityenhance",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 105,
      "serviceId": "swdae2133425",
      "serviceName": "红酒识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/redWineIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 106,
      "serviceId": "swdae2133426",
      "serviceName": "门脸识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/shopfrontIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 107,
      "serviceId": "swdae2133427",
      "serviceName": "天空分割",
      "requestUrl": "https://www.yzsophia.com/ai/image/skyseg",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 108,
      "serviceId": "swdae2133428",
      "serviceName": "拉伸图像恢复",
      "requestUrl": "https://www.yzsophia.com/ai/image/stretchrestore",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 109,
      "serviceId": "swdae2133429",
      "serviceName": "图像风格转换",
      "requestUrl": "https://www.yzsophia.com/ai/image/styletrans",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 110,
      "serviceId": "swdae2133430",
      "serviceName": "车流统计",
      "requestUrl": "https://www.yzsophia.com/ai/image/trafficFlowSti",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 111,
      "serviceId": "swdae2133431",
      "serviceName": "菜品识别",
      "requestUrl": "https://www.yzsophia.com/ai/image/varietyIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 165,
      "serviceId": "swdae2133485",
      "serviceName": "物体识别",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/bodyIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 166,
      "serviceId": "swdae2133486",
      "serviceName": "美食图片识别",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/foodImage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 167,
      "serviceId": "swdae2133487",
      "serviceName": "图片翻译",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/nlpImageTranslate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 168,
      "serviceId": "swdae2133488",
      "serviceName": "语音翻译",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/nlpSpeechTranslate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 169,
      "serviceId": "swdae2133489",
      "serviceName": "看图说话",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/pictureDescribe",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 170,
      "serviceId": "swdae2133490",
      "serviceName": "场景识别",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/sceneBody",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 171,
      "serviceId": "swdae2133491",
      "serviceName": "多标签识别",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/tagIdentify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 172,
      "serviceId": "swdae2133492",
      "serviceName": "模糊图片识别",
      "requestUrl": "https://www.yzsophia.com/ai/imageReco/vagueImage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 4,
      "aiName": "图片识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ],
  "人体识别": [
    {
      "id": 34,
      "serviceId": "swdae2133354",
      "serviceName": "人体检测和属性识别",
      "requestUrl": "https://www.yzsophia.com/ai/body/attr",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 35,
      "serviceId": "swdae2133355",
      "serviceName": "危险行为识别",
      "requestUrl": "https://www.yzsophia.com/ai/body/danger",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 36,
      "serviceId": "swdae2133356",
      "serviceName": "驾驶行为分析",
      "requestUrl": "https://www.yzsophia.com/ai/body/driverbehavior",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 37,
      "serviceId": "swdae2133357",
      "serviceName": "指尖检测",
      "requestUrl": "https://www.yzsophia.com/ai/body/fingertip",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 38,
      "serviceId": "swdae2133358",
      "serviceName": "手势识别",
      "requestUrl": "https://www.yzsophia.com/ai/body/gesture",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 39,
      "serviceId": "swdae2133359",
      "serviceName": "人像渐变",
      "requestUrl": "https://www.yzsophia.com/ai/body/gradient",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 40,
      "serviceId": "swdae2133360",
      "serviceName": "手部关键点识别",
      "requestUrl": "https://www.yzsophia.com/ai/body/handanalysis",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 41,
      "serviceId": "swdae2133361",
      "serviceName": "人流量统计",
      "requestUrl": "https://www.yzsophia.com/ai/body/num",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 42,
      "serviceId": "swdae2133362",
      "serviceName": "人像分割",
      "requestUrl": "https://www.yzsophia.com/ai/body/segment",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 43,
      "serviceId": "swdae2133363",
      "serviceName": "皮肤检测",
      "requestUrl": "https://www.yzsophia.com/ai/body/skincolor",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 44,
      "serviceId": "swdae2133364",
      "serviceName": "人流量统计（动态版）",
      "requestUrl": "https://www.yzsophia.com/ai/body/tracking",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 197,
      "serviceId": "swdae2133364",
      "serviceName": "人流量统计（动态版）",
      "requestUrl": "http://127.0.0.1:8084/ai/body/tracking",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": "",
      "setup": "百度",
      "aiType": 7,
      "aiName": "人体识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": ""
    }
  ],
  "自然语言处理": [
    {
      "id": 112,
      "serviceId": "swdae2133432",
      "serviceName": "地址识别",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/address",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 113,
      "serviceId": "swdae2133433",
      "serviceName": "评论观点抽取",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/commentTag",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 114,
      "serviceId": "swdae2133434",
      "serviceName": "依存句法分析",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/depparser",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 115,
      "serviceId": "swdae2133435",
      "serviceName": "对话情绪识别",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/emotion",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 116,
      "serviceId": "swdae2133436",
      "serviceName": "垂直领域翻译",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/fieldtranslate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 117,
      "serviceId": "swdae2133437",
      "serviceName": "文章标签",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/keyword",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 118,
      "serviceId": "swdae2133438",
      "serviceName": "新闻摘要",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/newsSummary",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 119,
      "serviceId": "swdae2133439",
      "serviceName": "情感倾向分析",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/sentimentClassify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 120,
      "serviceId": "swdae2133440",
      "serviceName": "短文本相似度",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/simnet",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 121,
      "serviceId": "swdae2133441",
      "serviceName": "文本审核",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/textCensor",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 122,
      "serviceId": "swdae2133442",
      "serviceName": "文本纠错",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/textError",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 123,
      "serviceId": "swdae2133443",
      "serviceName": "文章分类",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/topic",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 124,
      "serviceId": "swdae2133444",
      "serviceName": "词向量标示",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/wordEmbVec",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 143,
      "serviceId": "swdae2133463",
      "serviceName": "招商引资搜索",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/inviteInvestmentSearch",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 144,
      "serviceId": "swdae2133464",
      "serviceName": "关键词搜索",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/keywordSearch",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 145,
      "serviceId": "swdae2133465",
      "serviceName": "京东句法分析--替换句法分析",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/lexer",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 146,
      "serviceId": "swdae2133466",
      "serviceName": "京东句法分析--替换句法分析",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/parser",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 147,
      "serviceId": "swdae2133467",
      "serviceName": "分词",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/participle",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 148,
      "serviceId": "swdae2133468",
      "serviceName": "分词Word数量统计",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/participleByWordCount",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 149,
      "serviceId": "swdae2133469",
      "serviceName": "分词词性对照表接口",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/participleContrast",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 150,
      "serviceId": "swdae2133470",
      "serviceName": "分词数量统计",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/participleCount",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 151,
      "serviceId": "swdae2133471",
      "serviceName": "京东短语挖掘--替换关键词提取",
      "requestUrl": "https://www.yzsophia.com/ai/jnlp/phraseExtract",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "结巴",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 180,
      "serviceId": "swdae2133500",
      "serviceName": "阿里在线语音合成",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/text2audio",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 181,
      "serviceId": "swdae2133501",
      "serviceName": "通用翻译",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/translateGeneral",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 182,
      "serviceId": "swdae2133502",
      "serviceName": "实时语音识别",
      "requestUrl": "https://www.yzsophia.com/ai/nlp/voiceRealTimeTranscriber",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 1,
      "aiName": "自然语言处理",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ],
  "文字识别": [
    {
      "id": 10,
      "serviceId": "swdae2133330",
      "serviceName": "银行卡识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/bankcard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 11,
      "serviceId": "swdae2133331",
      "serviceName": "驾驶证识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/driverlicense",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 12,
      "serviceId": "swdae2133332",
      "serviceName": "身份证识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/idcard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 13,
      "serviceId": "swdae2133333",
      "serviceName": "通用模板识别功能",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/template",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 14,
      "serviceId": "swdae2133334",
      "serviceName": "行驶证识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/vehiclelicense",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 21,
      "serviceId": "swdae2133341",
      "serviceName": "银行卡识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/bankcard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 22,
      "serviceId": "swdae2133342",
      "serviceName": "名片识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/businessCard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 23,
      "serviceId": "swdae2133343",
      "serviceName": "营业执照识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/businessLicense",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 24,
      "serviceId": "swdae2133344",
      "serviceName": "自定义OCR模板识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/custom",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 25,
      "serviceId": "swdae2133345",
      "serviceName": "驾驶证识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/drivingLicense",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 26,
      "serviceId": "swdae2133346",
      "serviceName": "获取职业OCR模板",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/getProfession",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 27,
      "serviceId": "swdae2133347",
      "serviceName": "获取模板列表",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/getTemplate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 28,
      "serviceId": "swdae2133348",
      "serviceName": "港澳通行证识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/HKExitentrypermit",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 29,
      "serviceId": "swdae2133349",
      "serviceName": "身份证识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/idcard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 30,
      "serviceId": "swdae2133350",
      "serviceName": "护照识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/passport",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 31,
      "serviceId": "swdae2133351",
      "serviceName": "增值税发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/vatInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 32,
      "serviceId": "swdae2133352",
      "serviceName": "机动车销售发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/vehicleInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 33,
      "serviceId": "swdae2133353",
      "serviceName": "行驶证识别",
      "requestUrl": "https://www.yzsophia.com/ai/bdocr/vehicleLicense",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 56,
      "serviceId": "swdae2133376",
      "serviceName": "通用高精度文字识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/accurate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 57,
      "serviceId": "swdae2133377",
      "serviceName": "行程单识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/airTicket",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 58,
      "serviceId": "swdae2133378",
      "serviceName": "银行卡识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/bankCard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 59,
      "serviceId": "swdae2133379",
      "serviceName": "出生医学证明识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/birthCertificate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 60,
      "serviceId": "swdae2133380",
      "serviceName": "名片识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/businessCard",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 61,
      "serviceId": "swdae2133381",
      "serviceName": "混合文字识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/finance",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 62,
      "serviceId": "swdae2133382",
      "serviceName": "表格文字识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/formOcrRequest",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 63,
      "serviceId": "swdae2133383",
      "serviceName": "公式识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/formula",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 64,
      "serviceId": "swdae2133384",
      "serviceName": "通用文字识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/general",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 65,
      "serviceId": "swdae2133385",
      "serviceName": "手写识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/handwriting",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 66,
      "serviceId": "swdae2133386",
      "serviceName": "户口识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/householdRegister",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 67,
      "serviceId": "swdae2133387",
      "serviceName": "保单识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/insuranceDocuments",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 68,
      "serviceId": "swdae2133388",
      "serviceName": "通用发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/invoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 69,
      "serviceId": "swdae2133389",
      "serviceName": "车牌识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/licensePlate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 70,
      "serviceId": "swdae2133390",
      "serviceName": "彩票识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/lottery",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 71,
      "serviceId": "swdae2133391",
      "serviceName": "数字识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/numbers",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 72,
      "serviceId": "swdae2133392",
      "serviceName": "二维码识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/qrcode",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 73,
      "serviceId": "swdae2133393",
      "serviceName": "定额发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/quotaInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 74,
      "serviceId": "swdae2133394",
      "serviceName": "行程单识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/receipt",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 75,
      "serviceId": "swdae2133395",
      "serviceName": "印章识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/seal",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 76,
      "serviceId": "swdae2133396",
      "serviceName": "台湾通行证识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/taiwanExitentrypermit",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 77,
      "serviceId": "swdae2133397",
      "serviceName": "出租车票识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/taxiReceipt",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 78,
      "serviceId": "swdae2133398",
      "serviceName": "通行费发票",
      "requestUrl": "https://www.yzsophia.com/ai/text/toll",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 79,
      "serviceId": "swdae2133399",
      "serviceName": "火车票识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/trainTicket",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 80,
      "serviceId": "swdae2133400",
      "serviceName": "车辆合格证识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/vehicleCertificate",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 81,
      "serviceId": "swdae2133401",
      "serviceName": "vin识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/vinCode",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 82,
      "serviceId": "swdae2133402",
      "serviceName": "网络图片识别",
      "requestUrl": "https://www.yzsophia.com/ai/text/webImage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 152,
      "serviceId": "swdae2133472",
      "serviceName": "算式识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/arithmeticOCR",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 153,
      "serviceId": "swdae2133473",
      "serviceName": "数学试题识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/eduPaperOCR",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 154,
      "serviceId": "swdae2133474",
      "serviceName": "数据公式",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/formulaOCR",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 155,
      "serviceId": "swdae2133475",
      "serviceName": "保险单据识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/insuranceBillOCR",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 156,
      "serviceId": "swdae2133476",
      "serviceName": "表格识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/recognizeTableOCR",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 157,
      "serviceId": "swdae2133477",
      "serviceName": "增值税票据识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/tInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 174,
      "serviceId": "swdae2133494",
      "serviceName": "机票行程单识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/airInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 175,
      "serviceId": "swdae2133495",
      "serviceName": "机动车发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/carInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 176,
      "serviceId": "swdae2133496",
      "serviceName": "增值税票据识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/invoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 177,
      "serviceId": "swdae2133497",
      "serviceName": "定额发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/quotaInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 178,
      "serviceId": "swdae2133498",
      "serviceName": "出租车机打发票识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/texInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 179,
      "serviceId": "swdae2133499",
      "serviceName": "火车票识别",
      "requestUrl": "https://www.yzsophia.com/ai/ocr/trainInvoice",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "阿里云",
      "aiType": 3,
      "aiName": "文字识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ],
  "人脸识别": [
    {
      "id": 2,
      "serviceId": "swdae2133322",
      "serviceName": "人脸美颜",
      "requestUrl": "https://www.yzsophia.com/ai/face/beautifyv1",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 3,
      "serviceId": "swdae2133323",
      "serviceName": "人脸美型",
      "requestUrl": "https://www.yzsophia.com/ai/face/beautifyv2",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 4,
      "serviceId": "swdae2133324",
      "serviceName": "人脸对比",
      "requestUrl": "https://www.yzsophia.com/ai/face/compare",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 5,
      "serviceId": "swdae2133325",
      "serviceName": "人脸检测和分析",
      "requestUrl": "https://www.yzsophia.com/ai/face/detect",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 6,
      "serviceId": "swdae2133326",
      "serviceName": "3D人脸重建",
      "requestUrl": "https://www.yzsophia.com/ai/face/facereconstruction",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 7,
      "serviceId": "swdae2133327",
      "serviceName": "面部特征分析",
      "requestUrl": "https://www.yzsophia.com/ai/face/featureanalysis",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 8,
      "serviceId": "swdae2133328",
      "serviceName": "稠密关键点",
      "requestUrl": "https://www.yzsophia.com/ai/face/keypoints",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 9,
      "serviceId": "swdae2133329",
      "serviceName": "皮肤分析",
      "requestUrl": "https://www.yzsophia.com/ai/face/skinanalysis",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "旷视",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 45,
      "serviceId": "swdae2133365",
      "serviceName": "人脸属性编辑",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/editattr",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 46,
      "serviceId": "swdae2133366",
      "serviceName": "人脸3D生成",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/face3dprocess",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 47,
      "serviceId": "swdae2133367",
      "serviceName": "在线活体检测",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/faceverify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 48,
      "serviceId": "swdae2133368",
      "serviceName": "人脸对比",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/match",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 49,
      "serviceId": "swdae2133369",
      "serviceName": "人脸融合",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/merge",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 50,
      "serviceId": "swdae2133370",
      "serviceName": "人脸搜索",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/search",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 51,
      "serviceId": "swdae2133371",
      "serviceName": "人像动漫化",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/selfieanime",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 52,
      "serviceId": "swdae2133372",
      "serviceName": "视频活体检测",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/sessioncode",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 53,
      "serviceId": "swdae2133373",
      "serviceName": "身份验证",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/verify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 54,
      "serviceId": "swdae2133374",
      "serviceName": "视频活体检测",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/vidioVerify",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 55,
      "serviceId": "swdae2133375",
      "serviceName": "讯飞人脸水印照比对",
      "requestUrl": "https://www.yzsophia.com/ai/bdface/watermarkverification",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "百度",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 158,
      "serviceId": "swdae2133478",
      "serviceName": "跨年龄人脸识别",
      "requestUrl": "https://www.yzsophia.com/ai/face/detectcrossage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 159,
      "serviceId": "swdae2133479",
      "serviceName": "颜龄检测",
      "requestUrl": "https://www.yzsophia.com/ai/face/faceage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 160,
      "serviceId": "swdae2133480",
      "serviceName": "人脸美妆",
      "requestUrl": "https://www.yzsophia.com/ai/face/facecosmetic",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 161,
      "serviceId": "swdae2133481",
      "serviceName": "人脸变妆",
      "requestUrl": "https://www.yzsophia.com/ai/face/facedecoration",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 162,
      "serviceId": "swdae2133482",
      "serviceName": "五官定位",
      "requestUrl": "https://www.yzsophia.com/ai/face/faceshape",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 163,
      "serviceId": "swdae2133483",
      "serviceName": "大头贴",
      "requestUrl": "https://www.yzsophia.com/ai/face/facesticker",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 164,
      "serviceId": "swdae2133484",
      "serviceName": "图片滤镜",
      "requestUrl": "https://www.yzsophia.com/ai/face/imgfilter",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    },
    {
      "id": 173,
      "serviceId": "swdae2133493",
      "serviceName": "换脸甄别",
      "requestUrl": "https://www.yzsophia.com/ai/faceCloud/faceChangeImage",
      "createTime": "2021-01-18 10:23:01",
      "serviceDesc": null,
      "setup": "腾讯",
      "aiType": 6,
      "aiName": "人脸识别",
      "status": 1,
      "freeNum": 1000,
      "freeType": 2,
      "basicQps": 5,
      "sdkDowmLoadUrl": null
    }
  ]
}
